#!/usr/bin/env bash
set -euo pipefail

# ── MDTeX Studio Installer (Linux / macOS) ────────────────────────────────────
# Installs the `publisher` command and initialises user directories.
# Safe to run multiple times (idempotent).
#
# The command contract is identical on Windows and Linux:
#   publisher start | init | doctor | update | build <article> --target <t> | version

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="publisher"
MIN_NODE_MAJOR=18

red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

echo ""
bold "MDTeX Studio Installer"
echo "======================"
echo ""

# ── 1. Detect OS ───────────────────────────────────────────────────────────────

OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux";;
  Darwin*) PLATFORM="macos";;
  *)       red "Unsupported OS: $OS"; exit 1;;
esac
echo "Platform: $PLATFORM"

# ── 2. Check Node.js ──────────────────────────────────────────────────────────

if ! command -v node &>/dev/null; then
  red "Error: Node.js is not installed."
  echo "Install Node.js >= $MIN_NODE_MAJOR from https://nodejs.org/"
  exit 1
fi

NODE_VERSION="$(node -v)"
NODE_MAJOR="$(echo "$NODE_VERSION" | sed 's/v\([0-9]*\).*/\1/')"
if [ "$NODE_MAJOR" -lt "$MIN_NODE_MAJOR" ]; then
  red "Error: Node.js $NODE_VERSION is too old. Need >= v$MIN_NODE_MAJOR."
  exit 1
fi
echo "Node.js: $NODE_VERSION"
NODE_BIN="$(command -v node)"

if ! command -v npm &>/dev/null; then
  red "Error: npm is not installed."
  exit 1
fi
echo "npm: $(npm -v)"

if ! command -v git &>/dev/null; then
  yellow "Warning: git not found. 'publisher update' will not work."
else
  echo "git: $(git --version | head -1)"
fi

# ── 3. Pull latest (matches install.ps1 behaviour) ────────────────────────────

cd "$SCRIPT_DIR"
if [ "${MDTEX_SKIP_PULL:-0}" != "1" ] && command -v git &>/dev/null && [ -d "$SCRIPT_DIR/.git" ]; then
  echo ""
  bold "Pulling latest changes..."
  if git pull --ff-only 2>&1 | sed 's/^/  /'; then :; else
    yellow "Warning: git pull failed. Continuing with the current checkout."
  fi
fi

echo ""

# ── 4. Install dependencies ──────────────────────────────────────────────────

bold "Installing dependencies..."
npm install --no-audit --no-fund 2>&1 | tail -3
echo ""

# ── 5. Build UI ───────────────────────────────────────────────────────────────

bold "Building UI..."
npx vite build 2>&1 | grep -E '(built in|✓|modules transformed)' || true
echo ""

# ── 6. Initialize user directories ───────────────────────────────────────────

bold "Initializing user directories..."
node "$SCRIPT_DIR/src/cli/index.js" init
echo ""

# ── 7. Install the `publisher` command ────────────────────────────────────────

bold "Setting up the publisher command..."

USER_BIN="${MDTEX_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$USER_BIN"

WRAPPER="$USER_BIN/$APP_NAME"
cat > "$WRAPPER" << WRAPPER_EOF
#!/usr/bin/env bash
# MDTeX Studio launcher - generated by install.sh
exec "$NODE_BIN" "$SCRIPT_DIR/src/cli/index.js" "\$@"
WRAPPER_EOF
chmod +x "$WRAPPER"
echo "  Installed: $WRAPPER"

# Put the bin directory on PATH automatically, once, with a marker so repeated
# installs never append a second time.
MARKER="# added by MDTeX Studio installer"
add_path_line() {
  local profile="$1"
  [ -f "$profile" ] || return 1
  if grep -qF "$MARKER" "$profile"; then
    echo "  PATH already configured in $profile"
    return 0
  fi
  {
    echo ""
    echo "$MARKER"
    echo "case \":\$PATH:\" in *\":$USER_BIN:\"*) ;; *) export PATH=\"$USER_BIN:\$PATH\" ;; esac"
  } >> "$profile"
  echo "  PATH configured in $profile"
  return 0
}

if echo "$PATH" | tr ':' '\n' | grep -qx "$USER_BIN"; then
  echo "  $USER_BIN is already on PATH"
else
  CONFIGURED=0
  case "$(basename "${SHELL:-bash}")" in
    zsh)  PROFILES="$HOME/.zshrc $HOME/.zprofile";;
    bash) PROFILES="$HOME/.bashrc $HOME/.bash_profile $HOME/.profile";;
    *)    PROFILES="$HOME/.profile $HOME/.bashrc";;
  esac
  for profile in $PROFILES; do
    if add_path_line "$profile"; then CONFIGURED=1; break; fi
  done
  if [ "$CONFIGURED" -eq 0 ]; then
    touch "$HOME/.profile"
    add_path_line "$HOME/.profile" && CONFIGURED=1
  fi
  echo ""
  yellow "  Open a new terminal (or run: export PATH=\"$USER_BIN:\$PATH\") to use \`publisher\`."
fi

echo ""

# ── 8. LaTeX detection ────────────────────────────────────────────────────────

bold "Checking for LaTeX..."
node "$SCRIPT_DIR/src/cli/index.js" latex 2>&1 | sed 's/^/  /'
echo ""

# ── 9. Self-test ──────────────────────────────────────────────────────────────

bold "Running self-test..."
if node "$SCRIPT_DIR/scripts/selftest.js"; then
  echo ""
  green "Self-test passed."
else
  echo ""
  yellow "Warning: Some self-tests failed. Run 'publisher doctor' for details."
fi

# ── 10. Done ──────────────────────────────────────────────────────────────────

echo ""
bold "Installation complete!"
echo ""
echo "Start MDTeX Studio:"
echo "  publisher start"
echo ""
echo "Other commands (identical on Windows and Linux):"
echo "  publisher init"
echo "  publisher doctor"
echo "  publisher update"
echo "  publisher build <article-dir> --target pdf"
echo "  publisher build <article-dir> --target wechat"
echo "  publisher version"
echo ""
echo "Configuration:  ~/.config/$APP_NAME/"
echo "User themes:    ~/.local/share/$APP_NAME/themes/"
echo "Workspace:      ~/.local/share/$APP_NAME/workspace/"
echo ""
